# Generated by Django 5.1.6 on 2025-02-19 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0003_remove_donation_campaign_remove_donation_donor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Medical', 'Medical'), ('Startup', 'Startup')], max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('company_content', models.TextField(blank=True, null=True)),
                ('authorized_doc', models.FileField(blank=True, null=True, upload_to='fundraiser_docs/')),
                ('company_evaluation', models.FileField(blank=True, null=True, upload_to='fundraiser_docs/')),
                ('why_fundraise', models.TextField(blank=True, null=True)),
                ('pre_existing_loans', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
